# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.9

# Mod Properties
mod_version=1.0.9-1.21.1
maven_group=com.example
archives_base_name=loot_n_explore

# Dependencies
fabric_version=0.103.0+1.21.1
cloth_config_version=15.0.130
tiny_config_version=2.3.2
mixin_extras_version=0.1.1

# Optional
spell_power_version=1.3.0+1.21.1
player_anim_version=2.0.0-alpha1+1.21
trinkets_version=3.10.0
spell_engine_version=1.6.12+1.21.1
azure_lib_armor_version=2.3.3
azure_mc_version=1.21.1
azure_lib_version=3.0.1
more_rpg_classes_version=2.2.3-1.21.1
witcher_version= 2.4.7-1.21
ranged_weapon_api_version=2.0.4+1.21.1
structure_pool_api_version=1.1.1+1.21.1
thermoo_version=v4.4