package more_rpg_loot.blocks;

import net.minecraft.block.Block;
import net.minecraft.data.client.BlockStateModelGenerator;
import net.minecraft.data.client.ItemModelGenerator;
import net.minecraft.data.client.Models;
import net.minecraft.item.Item;
import net.minecraft.util.Identifier;

import static more_rpg_loot.RPGLoot.MOD_ID;

/**
 * Defines how a block's model should be generated in datagen.
 * Different model types correspond to different generation methods in BlockStateModelGenerator.
 */
public sealed interface ModelType {

    /**
     * Generates the block model using the specified strategy.
     */
    void generate(BlockStateModelGenerator generator, Block block);

    /**
     * Generates the item model if needed. Default: no item model generation (uses block model).
     */
    default void generateItemModel(ItemModelGenerator generator, Item item, String blockName) {
        // By default, items use the block model - no special generation needed
    }

    /**
     * Simple cube with all sides using the same texture.
     * Uses: registerCubeAllModelTexturePool
     */
    record CubeAll() implements ModelType {
        @Override
        public void generate(BlockStateModelGenerator generator, Block block) {
            generator.registerCubeAllModelTexturePool(block);
        }
    }

    /**
     * Simple cube reusing a texture from another namespace (e.g. a vanilla block) instead of
     * shipping this mod's own texture.
     */
    record ExistingTexture(Identifier textureId) implements ModelType {
        @Override
        public void generate(BlockStateModelGenerator generator, Block block) {
            // Handled explicitly in ModModelProvider - needs a texture pool keyed by an external id
        }
    }

    /**
     * Cube with different textures for bottom, top, and sides.
     * Uses: cube_bottom_top parent model
     * Requires: name_bottom.png, name_top.png, name_side.png textures
     */
    record CubeBottomTop() implements ModelType {
        @Override
        public void generate(BlockStateModelGenerator generator, Block block) {
            generator.registerSingleton(block, net.minecraft.data.client.TexturedModel.CUBE_BOTTOM_TOP);
        }
    }

    /**
     * Lantern block (like soul lantern).
     * Uses: registerLantern for block model (which also auto-generates item model)
     * Note: This auto-generates the item model too. For custom item texture paths, use Custom().
     */
    record Lantern() implements ModelType {
        @Override
        public void generate(BlockStateModelGenerator generator, Block block) {
            generator.registerLantern(block);
        }

        // registerLantern automatically handles item model - no custom generation needed
    }

    /**
     * Flower pot plant (requires both the flower block and potted variant).
     * Uses: registerFlowerPotPlant
     */
    record FlowerPot(Block pottedBlock, BlockStateModelGenerator.TintType tintType) implements ModelType {
        @Override
        public void generate(BlockStateModelGenerator generator, Block block) {
            generator.registerFlowerPotPlant(block, pottedBlock, tintType);
        }
    }

    /**
     * Block that references a vanilla parent model with custom textures.
     * Example: frozen_chain references "block/chain" parent
     */
    record ParentReference(String parentModel) implements ModelType {
        @Override
        public void generate(BlockStateModelGenerator generator, Block block) {
            // Parent reference models are typically handled manually or with custom JSON
            // Skip generation - model file must exist manually
        }
    }

    /**
     * Stairs/Slab/Wall variants that belong to a texture pool.
     * These are handled by the base block's CubeAll generation.
     */
    record PoolVariant(Block baseBlock, VariantType variantType) implements ModelType {
        public enum VariantType { STAIRS, SLAB, WALL }

        @Override
        public void generate(BlockStateModelGenerator generator, Block block) {
            // Pool variants are generated by the base block's texture pool
            // This is handled specially in ModModelProvider
        }
    }

    /**
     * Custom or complex model that's created manually (e.g., Blockbench models).
     * Skip datagen for block model.
     * @param generateItemModel if true, generates item/generated model with texture from item/blocks/
     */
    record Custom(boolean generateItemModel) implements ModelType {
        public Custom() {
            this(false);
        }

        @Override
        public void generate(BlockStateModelGenerator generator, Block block) {
            // Custom models are handled manually - skip generation
        }

        @Override
        public void generateItemModel(ItemModelGenerator generator, Item item, String blockName) {
            if (generateItemModel) {
                // Generate item model with texture from item/blocks/ directory
                Models.GENERATED.upload(
                    Identifier.of(MOD_ID, "item/" + blockName),
                    net.minecraft.data.client.TextureMap.layer0(
                        Identifier.of(MOD_ID, "item/blocks/" + blockName)
                    ),
                    generator.writer
                );
            }
        }
    }

    /**
     * Simple block item model (uses block model as parent).
     * Most blocks use this by default.
     */
    record SimpleBlockItem() implements ModelType {
        @Override
        public void generate(BlockStateModelGenerator generator, Block block) {
            // This is handled automatically by registerSimpleState
            generator.registerSimpleState(block);
        }
    }
}
